/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package beadbox;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author albert
 */
public class PlayerOverviewFragment extends javax.swing.JPanel {

    /**
     * Creates new form PlayerOverviewFragment
     */
    int TRACKHEIGHT = getHeight()/8;
    int BEADHEIGHT = 50, page = 1, curChapter=0;
    boolean[] activeBars= new boolean[8];
    private final safeColors safeColor ;
    
    @Override
    protected void paintComponent(Graphics g) {
        
        TRACKHEIGHT = getHeight()/8;
        Graphics2D g2d = (Graphics2D) g;                
        super.paintComponent(g2d);
        g2d.setColor(Color.BLACK);
        g2d.setStroke(new BasicStroke(1));
        g2d.drawLine(0, TRACKHEIGHT, getWidth(), TRACKHEIGHT);
        g2d.drawLine(0, TRACKHEIGHT*2, getWidth(), TRACKHEIGHT*2);
        g2d.drawLine(0, TRACKHEIGHT*3, getWidth(), TRACKHEIGHT*3);
        g2d.drawLine(0, TRACKHEIGHT*4, getWidth(), TRACKHEIGHT*4);
        g2d.drawLine(0, TRACKHEIGHT*5, getWidth(), TRACKHEIGHT*5);
        g2d.drawLine(0, TRACKHEIGHT*6, getWidth(), TRACKHEIGHT*6);
        g2d.drawLine(0, TRACKHEIGHT*7, getWidth(), TRACKHEIGHT*7);
        
        if(activeBars[0]){
            g2d.setColor(safeColor.pickColor(50, 1));
            g2d.fillRect(0, TRACKHEIGHT*0, getWidth(), TRACKHEIGHT);          
        }
        if(activeBars[1]){
            g2d.setColor(safeColor.pickColor(50, 2));
            g2d.fillRect(0, TRACKHEIGHT*1, getWidth(), TRACKHEIGHT);          
        }
        if(activeBars[2]){
            g2d.setColor(safeColor.pickColor(50, 3));
            g2d.fillRect(0, TRACKHEIGHT*2, getWidth(), TRACKHEIGHT);          
        }
        if(activeBars[3]){
            g2d.setColor(safeColor.pickColor(50, 4));
            g2d.fillRect(0, TRACKHEIGHT*3, getWidth(), TRACKHEIGHT);          
        }
        if(activeBars[4]){
            g2d.setColor(safeColor.pickColor(50, 5));
            g2d.fillRect(0, TRACKHEIGHT*4, getWidth(), TRACKHEIGHT);          
        }
        if(activeBars[5]){
            g2d.setColor(safeColor.pickColor(50, 6));
            g2d.fillRect(0, TRACKHEIGHT*5, getWidth(), TRACKHEIGHT);          
        }
        if(activeBars[6]){
            g2d.setColor(safeColor.pickColor(50, 7));
            g2d.fillRect(0, TRACKHEIGHT*6, getWidth(), TRACKHEIGHT);          
        }
        if(activeBars[7]){
            g2d.setColor(safeColor.pickColor(50, 8));
            g2d.fillRect(0, TRACKHEIGHT*7, getWidth(), TRACKHEIGHT);          
        }
        
        repaint ();
    }

    /**
     * Creates new form BeadPlayer
     */
    public PlayerOverviewFragment() {
        initComponents(); 
        safeColor = new safeColors();
        
    }
    
    public void setBeadBars(int track, boolean val){
        if (track < 9){
            activeBars[track-1]=val;
        }
    }
    
    public void clear(){
        for(int i=0; i<activeBars.length; i++){
            activeBars[i] = false;
        }
    }
    
    public void cleartrack(int track){
        activeBars[track] = false;        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(110, 110, 110));
        setPreferredSize(new java.awt.Dimension(50, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
