/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package beadbox;

import java.awt.Color;
import java.util.ArrayList;

/**
 *
 * @author albert & somang
 */
public class PlayerOverview extends javax.swing.JPanel {

    /**
     * Creates new form PlayerOverview
     */  
    int activePage = 1;
    Color defaultColor;
    ArrayList <PlayerOverviewFragment> frags = new ArrayList();
    PlayerOverviewFragment tempFrag;
    

    public void setBead(int page, int track, boolean active){
        frags.get(page-1).setBeadBars(track, active);       
    }
    public void clearAll(){
        for (int i=0; i<frags.size(); i++){
            frags.get(i).clear();
        }
    }
    
    public void higlightFrag(int page){
        frags.get(activePage-1).setBackground(defaultColor);
        frags.get(page-1).setBackground(Color.WHITE);
        activePage = page;
    }
    
    public void createFrags(){        
        frags.add(playerOverviewFragment1);
        frags.add(playerOverviewFragment2);
        frags.add(playerOverviewFragment3);
        frags.add(playerOverviewFragment4);
        frags.add(playerOverviewFragment5);
        frags.add(playerOverviewFragment6);
        frags.add(playerOverviewFragment7);
        frags.add(playerOverviewFragment8);
        frags.add(playerOverviewFragment9);
        frags.add(playerOverviewFragment10);
        frags.add(playerOverviewFragment11);
        frags.add(playerOverviewFragment12);
        frags.add(playerOverviewFragment13);
        frags.add(playerOverviewFragment14);
        frags.add(playerOverviewFragment15);
    }
    
    /**
     * Creates new form BeadPlayer
     */
    public PlayerOverview() {
        initComponents();
        createFrags(); 
        defaultColor = frags.get(0).getBackground();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playerOverviewFragment1 = new beadbox.PlayerOverviewFragment();
        playerOverviewFragment2 = new beadbox.PlayerOverviewFragment();
        playerOverviewFragment3 = new beadbox.PlayerOverviewFragment();
        playerOverviewFragment4 = new beadbox.PlayerOverviewFragment();
        playerOverviewFragment5 = new beadbox.PlayerOverviewFragment();
        playerOverviewFragment6 = new beadbox.PlayerOverviewFragment();
        playerOverviewFragment7 = new beadbox.PlayerOverviewFragment();
        playerOverviewFragment8 = new beadbox.PlayerOverviewFragment();
        playerOverviewFragment9 = new beadbox.PlayerOverviewFragment();
        playerOverviewFragment10 = new beadbox.PlayerOverviewFragment();
        playerOverviewFragment11 = new beadbox.PlayerOverviewFragment();
        playerOverviewFragment12 = new beadbox.PlayerOverviewFragment();
        playerOverviewFragment13 = new beadbox.PlayerOverviewFragment();
        playerOverviewFragment14 = new beadbox.PlayerOverviewFragment();
        playerOverviewFragment15 = new beadbox.PlayerOverviewFragment();

        setBackground(new java.awt.Color(250, 250, 250));
        setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        playerOverviewFragment1.setBackground(new java.awt.Color(110, 110, 110));

        javax.swing.GroupLayout playerOverviewFragment1Layout = new javax.swing.GroupLayout(playerOverviewFragment1);
        playerOverviewFragment1.setLayout(playerOverviewFragment1Layout);
        playerOverviewFragment1Layout.setHorizontalGroup(
            playerOverviewFragment1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        playerOverviewFragment1Layout.setVerticalGroup(
            playerOverviewFragment1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        playerOverviewFragment2.setBackground(new java.awt.Color(110, 110, 110));

        javax.swing.GroupLayout playerOverviewFragment2Layout = new javax.swing.GroupLayout(playerOverviewFragment2);
        playerOverviewFragment2.setLayout(playerOverviewFragment2Layout);
        playerOverviewFragment2Layout.setHorizontalGroup(
            playerOverviewFragment2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        playerOverviewFragment2Layout.setVerticalGroup(
            playerOverviewFragment2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        playerOverviewFragment3.setBackground(new java.awt.Color(110, 110, 110));

        javax.swing.GroupLayout playerOverviewFragment3Layout = new javax.swing.GroupLayout(playerOverviewFragment3);
        playerOverviewFragment3.setLayout(playerOverviewFragment3Layout);
        playerOverviewFragment3Layout.setHorizontalGroup(
            playerOverviewFragment3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        playerOverviewFragment3Layout.setVerticalGroup(
            playerOverviewFragment3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        playerOverviewFragment4.setBackground(new java.awt.Color(110, 110, 110));

        javax.swing.GroupLayout playerOverviewFragment4Layout = new javax.swing.GroupLayout(playerOverviewFragment4);
        playerOverviewFragment4.setLayout(playerOverviewFragment4Layout);
        playerOverviewFragment4Layout.setHorizontalGroup(
            playerOverviewFragment4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        playerOverviewFragment4Layout.setVerticalGroup(
            playerOverviewFragment4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        playerOverviewFragment5.setBackground(new java.awt.Color(110, 110, 110));

        javax.swing.GroupLayout playerOverviewFragment5Layout = new javax.swing.GroupLayout(playerOverviewFragment5);
        playerOverviewFragment5.setLayout(playerOverviewFragment5Layout);
        playerOverviewFragment5Layout.setHorizontalGroup(
            playerOverviewFragment5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        playerOverviewFragment5Layout.setVerticalGroup(
            playerOverviewFragment5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        playerOverviewFragment6.setBackground(new java.awt.Color(110, 110, 110));

        javax.swing.GroupLayout playerOverviewFragment6Layout = new javax.swing.GroupLayout(playerOverviewFragment6);
        playerOverviewFragment6.setLayout(playerOverviewFragment6Layout);
        playerOverviewFragment6Layout.setHorizontalGroup(
            playerOverviewFragment6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        playerOverviewFragment6Layout.setVerticalGroup(
            playerOverviewFragment6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        playerOverviewFragment7.setBackground(new java.awt.Color(110, 110, 110));

        javax.swing.GroupLayout playerOverviewFragment7Layout = new javax.swing.GroupLayout(playerOverviewFragment7);
        playerOverviewFragment7.setLayout(playerOverviewFragment7Layout);
        playerOverviewFragment7Layout.setHorizontalGroup(
            playerOverviewFragment7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        playerOverviewFragment7Layout.setVerticalGroup(
            playerOverviewFragment7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        playerOverviewFragment8.setBackground(new java.awt.Color(110, 110, 110));

        javax.swing.GroupLayout playerOverviewFragment8Layout = new javax.swing.GroupLayout(playerOverviewFragment8);
        playerOverviewFragment8.setLayout(playerOverviewFragment8Layout);
        playerOverviewFragment8Layout.setHorizontalGroup(
            playerOverviewFragment8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        playerOverviewFragment8Layout.setVerticalGroup(
            playerOverviewFragment8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        playerOverviewFragment9.setBackground(new java.awt.Color(110, 110, 110));

        javax.swing.GroupLayout playerOverviewFragment9Layout = new javax.swing.GroupLayout(playerOverviewFragment9);
        playerOverviewFragment9.setLayout(playerOverviewFragment9Layout);
        playerOverviewFragment9Layout.setHorizontalGroup(
            playerOverviewFragment9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        playerOverviewFragment9Layout.setVerticalGroup(
            playerOverviewFragment9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        playerOverviewFragment10.setBackground(new java.awt.Color(110, 110, 110));

        javax.swing.GroupLayout playerOverviewFragment10Layout = new javax.swing.GroupLayout(playerOverviewFragment10);
        playerOverviewFragment10.setLayout(playerOverviewFragment10Layout);
        playerOverviewFragment10Layout.setHorizontalGroup(
            playerOverviewFragment10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        playerOverviewFragment10Layout.setVerticalGroup(
            playerOverviewFragment10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        playerOverviewFragment11.setBackground(new java.awt.Color(110, 110, 110));

        javax.swing.GroupLayout playerOverviewFragment11Layout = new javax.swing.GroupLayout(playerOverviewFragment11);
        playerOverviewFragment11.setLayout(playerOverviewFragment11Layout);
        playerOverviewFragment11Layout.setHorizontalGroup(
            playerOverviewFragment11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        playerOverviewFragment11Layout.setVerticalGroup(
            playerOverviewFragment11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        playerOverviewFragment12.setBackground(new java.awt.Color(110, 110, 110));

        javax.swing.GroupLayout playerOverviewFragment12Layout = new javax.swing.GroupLayout(playerOverviewFragment12);
        playerOverviewFragment12.setLayout(playerOverviewFragment12Layout);
        playerOverviewFragment12Layout.setHorizontalGroup(
            playerOverviewFragment12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        playerOverviewFragment12Layout.setVerticalGroup(
            playerOverviewFragment12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        playerOverviewFragment13.setBackground(new java.awt.Color(110, 110, 110));

        javax.swing.GroupLayout playerOverviewFragment13Layout = new javax.swing.GroupLayout(playerOverviewFragment13);
        playerOverviewFragment13.setLayout(playerOverviewFragment13Layout);
        playerOverviewFragment13Layout.setHorizontalGroup(
            playerOverviewFragment13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        playerOverviewFragment13Layout.setVerticalGroup(
            playerOverviewFragment13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        playerOverviewFragment14.setBackground(new java.awt.Color(110, 110, 110));

        javax.swing.GroupLayout playerOverviewFragment14Layout = new javax.swing.GroupLayout(playerOverviewFragment14);
        playerOverviewFragment14.setLayout(playerOverviewFragment14Layout);
        playerOverviewFragment14Layout.setHorizontalGroup(
            playerOverviewFragment14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        playerOverviewFragment14Layout.setVerticalGroup(
            playerOverviewFragment14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        playerOverviewFragment15.setBackground(new java.awt.Color(110, 110, 110));

        javax.swing.GroupLayout playerOverviewFragment15Layout = new javax.swing.GroupLayout(playerOverviewFragment15);
        playerOverviewFragment15.setLayout(playerOverviewFragment15Layout);
        playerOverviewFragment15Layout.setHorizontalGroup(
            playerOverviewFragment15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        playerOverviewFragment15Layout.setVerticalGroup(
            playerOverviewFragment15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(playerOverviewFragment1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerOverviewFragment2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerOverviewFragment3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerOverviewFragment4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerOverviewFragment5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerOverviewFragment6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerOverviewFragment7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerOverviewFragment8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerOverviewFragment9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerOverviewFragment10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerOverviewFragment11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerOverviewFragment12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerOverviewFragment13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerOverviewFragment14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerOverviewFragment15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(playerOverviewFragment1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(playerOverviewFragment2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(playerOverviewFragment3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(playerOverviewFragment4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(playerOverviewFragment5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(playerOverviewFragment6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(playerOverviewFragment7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(playerOverviewFragment8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(playerOverviewFragment9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(playerOverviewFragment10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(playerOverviewFragment11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(playerOverviewFragment12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(playerOverviewFragment13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(playerOverviewFragment14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(playerOverviewFragment15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private beadbox.PlayerOverviewFragment playerOverviewFragment1;
    private beadbox.PlayerOverviewFragment playerOverviewFragment10;
    private beadbox.PlayerOverviewFragment playerOverviewFragment11;
    private beadbox.PlayerOverviewFragment playerOverviewFragment12;
    private beadbox.PlayerOverviewFragment playerOverviewFragment13;
    private beadbox.PlayerOverviewFragment playerOverviewFragment14;
    private beadbox.PlayerOverviewFragment playerOverviewFragment15;
    private beadbox.PlayerOverviewFragment playerOverviewFragment2;
    private beadbox.PlayerOverviewFragment playerOverviewFragment3;
    private beadbox.PlayerOverviewFragment playerOverviewFragment4;
    private beadbox.PlayerOverviewFragment playerOverviewFragment5;
    private beadbox.PlayerOverviewFragment playerOverviewFragment6;
    private beadbox.PlayerOverviewFragment playerOverviewFragment7;
    private beadbox.PlayerOverviewFragment playerOverviewFragment8;
    private beadbox.PlayerOverviewFragment playerOverviewFragment9;
    // End of variables declaration//GEN-END:variables
}
